### ISSUE TITLE
Add logout link

### ISSUE THREAD

**Issue by bbockelm** [HTPhenotyping/registration#8] opened 2020-05-11 21:45 UTC
We should provide a 'logout' link.  It's minimally useful in this case - but would be a nice to have a mechanism for people to easily switch IdPs (example: someone started with Google because it was convenient but then realized they need to use their university ID).

**Comment by JoshKarpel** [comment] 2020-05-11 21:46
Duplicate of #7 ;)

**Closed as completed by JoshKarpel** 2020-05-11 21:46 UTC
